// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1-AXMka1a_NhBhcj5TD92eqtbW0LdYs',
    appId: '1:141926629911:web:2328f6b96b158f3ae61252',
    messagingSenderId: '141926629911',
    projectId: 'core-wallet',
    authDomain: 'core-wallet.firebaseapp.com',
    storageBucket: 'core-wallet.appspot.com',
    measurementId: 'G-H4WVF028KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_Y4Dhf1v0-n9kc65BYBStMogXHlgaKE',
    appId: '1:141926629911:android:907d3dcd92784cdfe61252',
    messagingSenderId: '141926629911',
    projectId: 'core-wallet',
    storageBucket: 'core-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhP45xvumpX2gFeI7pPksrxd4vSNivOA',
    appId: '1:141926629911:ios:981f686b944ec223e61252',
    messagingSenderId: '141926629911',
    projectId: 'core-wallet',
    storageBucket: 'core-wallet.appspot.com',
    iosClientId: '141926629911-vjnnjqijh20be9si6lp6sd7nhp6mj3nl.apps.googleusercontent.com',
    iosBundleId: 'com.corewallet.corewallet',
  );
}
